import sys
from pathlib import Path

from sqlalchemy import text

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from db.database import engine


MIGRATION_SQL = """
create table if not exists public.tasks (
    id integer generated by default as identity primary key,
    job_id varchar unique,
    status varchar(30) not null default 'PENDING',
    result text,
    error text,
    created_at timestamp with time zone not null default now(),
    started_at timestamp with time zone,
    finished_at timestamp with time zone
);

alter table public.tasks
    add column if not exists task_type varchar(100),
    add column if not exists input_data jsonb,
    add column if not exists priority integer,
    add column if not exists assigned_agent varchar(100),
    add column if not exists assigned_at timestamp with time zone,
    add column if not exists attempt_count integer,
    add column if not exists max_attempts integer;

update public.tasks
set task_type = 'LEGACY_RQ_TASK'
where task_type is null;

update public.tasks
set input_data = '{}'::jsonb
where input_data is null;

update public.tasks
set priority = 5
where priority is null;

update public.tasks
set attempt_count = 0
where attempt_count is null;

update public.tasks
set max_attempts = greatest(attempt_count, 1)
where max_attempts is null;

update public.tasks
set attempt_count = 1
where status in ('RUNNING', 'COMPLETED', 'FAILED')
  and attempt_count = 0;

update public.tasks
set assigned_at = coalesce(started_at, created_at)
where status in ('ASSIGNED', 'RUNNING')
  and assigned_at is null;

alter table public.tasks
    alter column task_type set not null,
    alter column task_type set default 'GENERIC_TASK',
    alter column input_data set not null,
    alter column input_data set default '{}'::jsonb,
    alter column priority set not null,
    alter column priority set default 5,
    alter column attempt_count set not null,
    alter column attempt_count set default 0,
    alter column max_attempts set not null,
    alter column max_attempts set default 1,
    alter column status set default 'PENDING',
    alter column created_at set default now();

do $migration$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'tasks_attempt_count_nonnegative'
          and conrelid = 'public.tasks'::regclass
    ) then
        alter table public.tasks
            add constraint tasks_attempt_count_nonnegative check (attempt_count >= 0);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'tasks_max_attempts_positive'
          and conrelid = 'public.tasks'::regclass
    ) then
        alter table public.tasks
            add constraint tasks_max_attempts_positive check (max_attempts >= 1);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'tasks_attempt_count_within_max'
          and conrelid = 'public.tasks'::regclass
    ) then
        alter table public.tasks
            add constraint tasks_attempt_count_within_max check (attempt_count <= max_attempts);
    end if;
end
$migration$;

create index if not exists idx_tasks_status
    on public.tasks (status);

create index if not exists idx_tasks_priority
    on public.tasks (priority desc);

create index if not exists idx_tasks_assigned_agent
    on public.tasks (assigned_agent);

create index if not exists idx_tasks_assigned_at
    on public.tasks (assigned_at);

create table if not exists public.task_events (
    id bigserial primary key,
    task_id integer not null references public.tasks (id) on delete cascade,
    event_type varchar(30) not null,
    from_status varchar(30),
    to_status varchar(30) not null,
    agent_name varchar(100),
    details jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_task_events_task_created
    on public.task_events (task_id, created_at desc);

create or replace function public.record_task_status_event()
returns trigger
language plpgsql
as $$
declare
    lifecycle_event varchar(30);
begin
    if tg_op = 'INSERT' then
        lifecycle_event := 'CREATED';
    elsif new.status is distinct from old.status then
        lifecycle_event := case
            when new.status = 'ASSIGNED' then 'ASSIGNED'
            when new.status = 'RUNNING' then 'STARTED'
            when new.status = 'COMPLETED' then 'COMPLETED'
            when new.status = 'FAILED' then 'FAILED'
            when new.status = 'CANCELLED' then 'CANCELLED'
            when new.status = 'PENDING'
              and old.status = 'RUNNING'
              and new.error is not null
              and new.attempt_count < new.max_attempts
                then 'RETRY_SCHEDULED'
            when new.status = 'PENDING' and old.status in ('ASSIGNED', 'RUNNING') then 'RECOVERED'
            else 'STATUS_CHANGED'
        end;
    else
        return new;
    end if;

    insert into public.task_events (
        task_id,
        event_type,
        from_status,
        to_status,
        agent_name,
        details
    )
    values (
        new.id,
        lifecycle_event,
        case when tg_op = 'UPDATE' then old.status else null end,
        new.status,
        case
            when new.assigned_agent is not null then new.assigned_agent
            when tg_op = 'UPDATE' then old.assigned_agent
            else null
        end,
        jsonb_strip_nulls(
            jsonb_build_object(
                'task_type', new.task_type,
                'priority', new.priority,
                'attempt_count', new.attempt_count,
                'max_attempts', new.max_attempts,
                'error', new.error,
                'previous_agent', case when tg_op = 'UPDATE' then old.assigned_agent else null end
            )
        )
    );

    return new;
end;
$$;

drop trigger if exists task_status_event_trigger on public.tasks;

create trigger task_status_event_trigger
after insert or update of status on public.tasks
for each row
execute function public.record_task_status_event();
"""


VERIFY_SQL = """
select column_name, data_type, is_nullable, column_default
from information_schema.columns
where table_schema = 'public'
  and table_name = 'tasks'
  and column_name in (
      'task_type',
      'input_data',
      'priority',
      'assigned_agent',
      'assigned_at',
      'attempt_count',
      'max_attempts',
      'status',
      'created_at'
  )
order by ordinal_position
"""

EVENT_VERIFY_SQL = """
select column_name, data_type, is_nullable, column_default
from information_schema.columns
where table_schema = 'public'
  and table_name = 'task_events'
order by ordinal_position
"""

TRIGGER_VERIFY_SQL = """
select exists (
    select 1
    from information_schema.triggers
    where event_object_schema = 'public'
      and event_object_table = 'tasks'
      and trigger_name = 'task_status_event_trigger'
)
"""


def main() -> None:
    with engine.begin() as connection:
        connection.execute(text(MIGRATION_SQL))
        columns = connection.execute(text(VERIFY_SQL)).mappings().all()
        event_columns = connection.execute(text(EVENT_VERIFY_SQL)).mappings().all()
        trigger_exists = connection.execute(text(TRIGGER_VERIFY_SQL)).scalar_one()

    print("Migration completed: task schema and event history are present.")
    print("Verified public.tasks columns:")
    for column in columns:
        print(
            f"- {column['column_name']}: {column['data_type']} "
            f"nullable={column['is_nullable']} default={column['column_default']}"
        )

    print("Verified public.task_events columns:")
    for column in event_columns:
        print(
            f"- {column['column_name']}: {column['data_type']} "
            f"nullable={column['is_nullable']} default={column['column_default']}"
        )
    print(f"Task status event trigger present: {trigger_exists}")


if __name__ == "__main__":
    main()
